openapi: 3.1.0
info:
  title: PDF Document Reader API
  description: API para obtener el contenido completo de documentos en Google Drive.
  version: "1.0.0"
servers:
  - url: https://pdf-doc-read.onrender.com
paths:
  /get_docs:
    get:
      summary: Obtiene todos los documentos de la carpeta en Google Drive
      operationId: getDocs
      responses:
        "200":
          description: Lista de documentos con su contenido completo
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                      description: Nombre del documento
                    contenido:
                      type: string
                      description: Contenido completo del documento
